workspace(name = "playgroundZ")

local_repository(
    name = "asiolib",
    path = "../ThirdParty/asio-1.18.0/",
)

local_repository(
    name = "fmtlib",
    path = "../ThirdParty/fmt/",
)

local_repository(
    name = "googletest",
    path = "../ThirdParty/GoogleTest/",
)

local_repository(
    name = "Nlohmann",
    path = "../ThirdParty/Nlohmann/",
)

local_repository(
    name = "spdloglib",
    path = "../ThirdParty/spdlog/",
)