workspace(name = "playgroundZ")

local_repository(
    name = "googletest",
    path = "../ThirdParty/GoogleTest/",
)

local_repository(
    name = "Nlohmann",
    path = "../ThirdParty/Nlohmann/",
)
