dist: bionic
sudo: required
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      
before install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb
  - sha256sum -c Tools/bazel_3.1.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.1.0-linux-x86_64.deb

script:
  - cd CMake && mkdir build && cd build && cmake .. && cmake --build . -- -j2
  - cd ../../Bazel && bazel build //:main
