dist: bionic
sudo: required
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux

git:
    submodules: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      
before install:
  # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # - git submodule update --init --recursive
  - mkdir temp && cd temp
  - wget https://github.com/bazelbuild/bazel/releases/download/3.6.0/bazel_3.6.0-linux-x86_64.deb
  - wget https://github.com/bazelbuild/bazel/releases/download/3.6.0/bazel_3.6.0-linux-x86_64.deb.sha256
  - sha256sum -c bazel_3.6.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.6.0-linux-x86_64.deb
  - cd .. && rm -rf temp

script:
  - cd CMake && mkdir build && cd build && cmake .. && cmake --build . -- -j2
  - cd ../../Bazel && bazel build //Main:main && bazel test //Main:awesome_class_test
